path: C:/Market/framework_v1_rebuild/data/datasets_A
train:
  - a0_base/images/train
  - a3_camera_addition/images/train
  - a1_synthetic_addition/images/train
val: a0_base/images/val

names:
  0: coke_zero
  1: think_protein_bar
  2: ziploc_box
