path: C:/Market/framework_v1_rebuild/data/datasets_B
train:
  - b0_base/images/train
  - b1_camera_addition/images/train
  - b2_phone_addition/images/train
val: b0_base/images/val

names:
  0: coke_zero
  1: oreo
  2: goodwipes
